name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - hotfix/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display Message
        run: echo "CI/CD Pipeline Started Successfully!"
